name: docker-build

on:
  push:
    branches:
      - cosmos/*/*
      - chains/*/*

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

      - name: Set BDJuno chain name üîß
        shell: bash
        run: echo "CHAIN_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Set BDJuno version üîß
        shell: bash
        run: echo "GITHUB_VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Prepare tags üè∑Ô∏è
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_BDJUNO_REPO }}
          CHAIN_NAME="${{env.CHAIN_NAME}}"
          VERSION="${{env.GITHUB_VERSION}}"
          TAGS="${DOCKER_IMAGE}:${CHAIN_NAME}-${VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up Docker Buildx üß∞
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub üë§
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push üì§
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
